#!/bin/bash
#
# Sunmi V2 vendor blob の Makefile 自動生成
#
# extract-files.sh 実行後、vendor/sunmi/v2/proprietary/ の全ファイルを
# vendor/sunmi/v2/v2-vendor.mk と vendor/sunmi/v2/BoardConfigVendor.mk と
# vendor/sunmi/v2/Android.mk に反映する。
#
# Usage: ./setup-makefiles.sh

set -e

DEVICE_TREE_DIR="$(dirname "$(readlink -f "$0")")"
VENDOR_DIR="$(cd "$DEVICE_TREE_DIR/../../../" && pwd)/vendor/sunmi/v2"
PROPRIETARY_DIR="$VENDOR_DIR/proprietary"

if [ ! -d "$PROPRIETARY_DIR" ]; then
    echo "[setup-makefiles] Error: $PROPRIETARY_DIR 存在しない。先に extract-files.sh を実行"
    exit 1
fi

# ---- v2-vendor.mk 生成 ----
cat > "$VENDOR_DIR/v2-vendor.mk" <<'EOF'
# Auto-generated by setup-makefiles.sh — vendor blob の LineageOS build system 組込
PRODUCT_SOONG_NAMESPACES += \
    vendor/sunmi/v2
EOF

echo 'PRODUCT_COPY_FILES += \' >> "$VENDOR_DIR/v2-vendor.mk"
(cd "$PROPRIETARY_DIR" && find . -type f | sed 's|^\./||' | while read f; do
    echo "    vendor/sunmi/v2/proprietary/$f:$f \\"
done) >> "$VENDOR_DIR/v2-vendor.mk"

# 末尾の \ を削除
sed -i '$ s/ \\$//' "$VENDOR_DIR/v2-vendor.mk"

# ---- BoardConfigVendor.mk 生成 (minimal) ----
cat > "$VENDOR_DIR/BoardConfigVendor.mk" <<'EOF'
# Auto-generated. vendor blob 追加時の BoardConfig override が必要ならここに。
EOF

# ---- Android.mk 生成 ----
cat > "$VENDOR_DIR/Android.mk" <<'EOF'
LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),v2)
# vendor blob は PRODUCT_COPY_FILES で直接配置するので、Android.mk 側は minimal
endif
EOF

echo "[setup-makefiles] 完了: v2-vendor.mk, BoardConfigVendor.mk, Android.mk 生成"
